# Schritt 1: Erstellen des Build-Images
FROM node:20 AS build

# Arbeitsverzeichnis erstellen
WORKDIR /app

# Quellcode kopieren und Build ausführen
COPY . .
RUN npm run build

# Schritt 2: Erstellen des Produktions-Images
FROM node:20 AS final

RUN addgroup --gid 1001 --system app && \
    adduser --no-create-home --shell /bin/false --disabled-password --uid 1001 --system --group app

# 'serve' installieren
RUN npm install -g serve

COPY --from=build /app/build ./build
# Statische Dateien kopieren
WORKDIR /app

RUN chown -c app /app

# App starten
CMD ["serve", "-s", "build", "-l", "3000"]

# Exponiere den Port
EXPOSE 3000
