version: "1.3"

services:
  assistantstt_module:
    build: .
    expose:
      - '5000'
    restart: unless-stopped
    env_file:
      - ../assistantstt_module.env
    healthcheck:
      test: curl --fail http://localhost:5000 || exit 1
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 5
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '2'
          memory: 512M
        reservations:
          cpus: '1'
          memory: 256M
    #depends_on:
    #  - otherservice
  # Serves as Load-Balancer
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - assistantstt_module
    ports:
      - '4000:4000'